# Copyright (c) 2026 Xavier Beheydt <xavier.beheydt@gmail.com>

# sshd_config defaults on Arch Linux
KbdInteractiveAuthentication no
UsePAM yes
PrintMotd no

# Add your `Port <port-nb>` in /etc/ssh/sshd_config.d/97-port.conf
PermitRootLogin no
PasswordAuthentication no
PubkeyAuthentication yes
# Add your `AllowUsers user1 user2 ...` -> /etc/ssh/sshd_config.d/98-users.conf
MaxAuthTries 3
X11Forwarding no
LogLevel VERBOSE
