# Copyright (c) 2026 Xavier Beheydt <xavier.beheydt@gmail.com>

# Reload the configuration file
bind r source-file ~/.config/tmux/tmux.conf \; display "Configuration reloaded!"

# Change the prefix key (default Ctrl-b)
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Navigation between panes without prefix
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Resizing panes without prefix
bind -n M-C-h resize-pane -L 5
bind -n M-C-j resize-pane -D 5
bind -n M-C-k resize-pane -U 5
bind -n M-C-l resize-pane -R 5

# Enable mouse support
set -g mouse on

# Window numbering starting from 1
set -g base-index 1
setw -g pane-base-index 1

# Automatic reloading of the configuration file
set -g automatic-rename on
set -g automatic-rename-format '#{pane_current_command}'

# Theme and appearance
set -g status-bg black
set -g status-fg white
set -g status-left '#[fg=green]#H #[fg=black]• #[fg=green,bright]#(uname -r)#[default]'
set -g status-right '#[fg=green,bg=default,bright]#(tmux-mem-cpu-load) #[fg=red,dim,bg=default]#(uptime | cut -f 4-5 -d " " | cut -f 1 -d ",") #[fg=white,bg=default]%a %H:%M:%S #[default] #[fg=blue]%Y-%m-%d'

# Duration for displaying messages
set -g display-time 2000

# Longer scrollback history
set -g history-limit 50000

# Vim-style copy-paste
setw -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

# Split panes with the same working directory
bind-key '|' split-window -h -c "#{pane_current_path}"
bind-key '\' split-window -v -c "#{pane_current_path}"
